project:
  type: book

book:
  title: "Archaeology Data Infrastructures"
  subtitle: "Data reuse potentials and limitations to modelling settlement systems (...)"
  author: 
    - name: "Petr Pajdla"
      institute: "Department of Archaeology and Museology, Faculty of Arts, Masaryk University"
      email: "petr.pajdla@proton.me"
      orcid-id: "0000-0001-7050-9572"
  date: "2022-11-02"
  favicon: cover.png
  search: true
  downloads: [pdf, docx]
  chapters:
    - index.qmd
    - intro.qmd
    - theory.qmd
    - data.qmd
    - discussion.qmd
    - summary.qmd
    - references.qmd

bibliography: "zotero_data_in_archaeology.bib"

highlight-style: tango

format:
  html:
    theme: 
      light: flatly # cosmo
      dark: darkly
  pdf:
    documentclass: scrreprt
  docx: default



