project:
  type: book

execute:
  freeze: auto

book:
  title: "Archaeology Data Infrastructures"
  subtitle: "Data reuse potentials and limitations to modelling settlement systems (...)"
  author:
    - name: "Petr Pajdla"
      email: "petr.pajdla@proton.me"
      orcid: "0000-0001-7050-9572"
      affiliations:
        - name: "Department of Archaeology and Museology, Faculty of Arts, Masaryk University"
        - name: "Institute of Archaeology, Czech Acad. Sci., Brno"
  date: today
  favicon: cover.png
  # cover-image: cover.png
  search: true
  sidebar:
    tools:
      - icon: github
        href: "https://github.com/petrpajdla/dataInfrastructures/"
  # reader-mode: true
  downloads: [pdf, docx]
  chapters:
    - index.qmd
    - chapters/intro.qmd
    - chapters/theory.qmd
    - chapters/method.qmd
    - chapters/data.qmd
#    - chapters/discussion.qmd
#    - chapters/summary.qmd
    - references.qmd
  appendices:
    - appendices/glossary.qmd
    # - appendices/software.qmd
citation: true

format:
  html:
    theme:
      light: lumen # cosmo flatly yeti lumen
      dark: slate # darkly slate
  pdf:
    documentclass: scrreprt
  docx: default
callout-appearance: simple
number-depth: 3
# highlight-style: tango

bibliography:
  - "zotero_data_in_archaeology.bib"
  - "zotero_reproducible_research.bib"
# csl: journal-of-computer-applications-in-archaeology.csl
csl: world-archaeology.csl
