project:
  type: book

execute:
  freeze: auto
  echo: false

book:
  title: "Archaeology Data Infrastructures"
  subtitle: "Data reuse potentials and limitations to modelling settlement systems (...)"
  author:
    - name: "Petr Pajdla"
      email: "petr.pajdla@proton.me"
      orcid: "0000-0001-7050-9572"
      affiliations:
        - name: "Department of Archaeology and Museology, Faculty of Arts, Masaryk University"
        - name: "Institute of Archaeology, Czech Acad Sci, Brno"
  date: today
  favicon: figs/cover.png
  # cover-image: cover.png
  search: true
  repo-url: "https://github.com/petrpajdla/dataInfrastructures/"
  repo-actions: [source, edit, issue]
  # sidebar:
  #   tools:
  #     - icon: github
  #       href: "https://github.com/petrpajdla/dataInfrastructures/"
  reader-mode: false
  downloads: [pdf, docx]
  chapters:
    - index.qmd
    - chapters/intro.qmd
    - chapters/theory.qmd
    # - chapters/method.qmd
    - chapters/data.qmd
    # - part: chapters/analysis.qmd
    #   chapters:
    #     - chapters/cs01.qmd
    # - chapters/discussion.qmd
    # - chapters/summary.qmd
    - biblio/references.qmd
  # appendices:
  #   - appendices/glossary.qmd
    # - appendices/software.qmd
citation: true

format:
  html:
    theme:
      light: lumen # cosmo flatly yeti lumen
      # dark: slate # darkly slate
    citation-location: margin
    reference-location: margin
  pdf:
    documentclass: scrreprt
  docx: default
callout-appearance: simple
number-depth: 3
# highlight-style: tango

toc-title: "Contents"

bibliography:
  # - biblio/library.bib
  - biblio/dataInfrastructures.bib
  # - biblio/zotero_data_in_archaeology.bib
  # - biblio/zotero_reproducible_research.bib
csl: https://www.zotero.org/styles/journal-of-computer-applications-in-archaeology
# csl: https://www.zotero.org/styles/harvard-european-archaeology
# csl: https://www.zotero.org/styles/world-archaeology
