# Data and materials {#sec-data}

::: {.callout-note}

## @sec-data details: {.unnumbered}

- How are data managed in this research.
  This is described in a data management plan.
- What data sources are available in the Czech Republic.
- What data models are most commonly used in Czech archaeology.
- How is the reality represented in the databases of the *Archaeological information system of the Czech Republic*.

:::

Sources of (archaeology) data in the Czech Republic, an overview:

Data models, datafication of past reality, simple vs complex data models;
Assessing findability, accessibility, interoperability, and reusability (FAIR) principles;
Cultural heritage management data vs research data domains;
Archaeological information system of the Czech Republic (AIS CR) as the main data infrastructure.

## Sources of archaeology data in the Czech Republic {#sec-sources}



### Archaeological information system of the Czech Republic {#sec-aiscr}

::: {.callout-warning}

## Conflict of interest disclosure

Since 2018 I am part of the AIS CR team at the *Institute of Archaeology, Czech Academy of Sciences, Brno* and since 2023 I am a member of the executive committee of this project.
This text is thus influenced by my inside view of how the infrastructure works.

:::

### Information system about archaeological data

### Legacy data sources

What is a legacy data source?

### Museum databases

### Other pre-existing data

There are several well published data sets covering the area of the Czech Republic in the [Journal of Open Archaeology Data](https://openarchaeologydata.metajnl.com/), the radiocarbon data by @tkac2021 and the Neolithic settlements data set by @pajdla2021.
These have an advantage of well formulated access and re-use policies, explicit licence and other conditions for use.


## Data management {#sec-dmp}

::: {.callout-note}

## Note

This section builds up on the project [*Data management in Archaeology*](https://www.phil.muni.cz/en/research/current-projects/57940) I cooperated on with Hana Kubelková in 2021 at the Department of Archaeology and Museology, Faculty of Arts, Masaryk University.

:::

Good data stewardship is a crucial element in *Open Science* [@mons2018, p. 1-5], an umbrella concept for how scientific research is conducted in a way that knowledge is reusable, modifiable and redistributable.
The data management plan (DMP) then stands at the very beginning of every such endeavour.
In its essence, a DMP is a stand-alone document detailing how data is handled at each of the steps in its life cycle.
This implies that it is not a static, but a living record of how the data was captured, created, curated, selected, analysed, interpreted, shared, and archived in the course of a project or after its end.
A DMP helps in adhering to the FAIR principles, i.e. making data findable, accessible, interoperable and reusable, a set of propositions enabling more effective knowledge discovery, collaboration, and data reuse [@wilkinson2016; @hollander2019].

The DMP included as @sec-apx-dmp is generated by [Data Stewardship Wizard](ds-wizard.org) [DSW, @pergl2019], an online tool dedicated to cooperative creation of data management plans.
It is included both as part of the text and as a standalone machine actionable file.
The notes below take into account templates for data management planning created in the [Ariadne project](https://vast-lab.org/dmp/index.html) [@doorn2022] as well as the DSW template.


### Data re-use

The work is predominantly based on re-using existing data.
The sources of data are listed and described in detail in the beginning of this chapter (ie. @sec-sources).

The single most complete source for archaeology data in the Czech Republic is without a doubt the AIS CR infrastructure.
The (meta)data of AIS CR infrastrucutre are accessed through a public OAI-PMH API.
This data is published under the CC BY-NC 4.0 International license, what makes the conditions for its use clear and transparent.

AIS CR data is aggregated in the ARIADNE infrastructure is accessed through SPARQL endpoint of the dedicated triple store.

The spatial data from ISAD is queried from an ArcGIS rest API.
The attributes for this data, ie. SAS database, is webscraped, because it is not published in any other machine-readable form.
The ISAD is licensed under CC BY-SA 4.0 International license and SAS metadata, as an integral part of the ISAD ecosystem falls under this license as well, although this fact is not explicitly stated on the website.

The data is accessed through custom scripts developed in the R language.

I presume that there are many pre-existing data sets in the Czech archaeology, but most of them are either inaccessible or not findable, i.e. we cannot be sure they even exist.

<!-- Wikidata?, OpenStreetMap?
Re-use
Are there pre-existing data?
License? Conditions for use?
How is it accessed? -->

#### Data creation and collection

No new data is collected or created per se, but re-used data sources are processed, remixed, interlinked etc. into new, different, data.
Vector spatial data is stored as geodatabases in [OGC GeoPackage](https://www.geopackage.org/), most of other data is stored as comma separated values (CSV) files.
Both formats are open standards, CSV is well suited for logn term preservation (LTP) of text-based data.
Preservation of code and data is planned in a sense that whole repository of this project will be deposited at Zenodo trustworthy repository and independently archived by the university.

<!-- - Creation and collection
Data formats?
Volumes of data? Suitable for LTP and sharing? -->

#### Controlled vocabularies and ontologies

<!-- Any used vocabularies, terminologies, ontologies? -->
I am explicitly using vocabularies that are inherent to data sources from which the data is reused.
A principal and authoritative vocabulary for archaeology and related fields is the *Getty Art & Architecture Thesaurus* ([AAT](https://www.getty.edu/research/tools/vocabularies/aat/)).
Getty *AAT* subjects are used by the *ARIADNE* infrastructure and many other archaeology infrastructures are mapping their vocabularies to the *AAT* subjects.
The emerging *ARIADNE* *AO_Cat* formal ontology is also taken into account when interacting with *ARIADNE* services.
The *AIS CR* vocabularies, although implicit to the data, are yet to be published.
A possibly incomplete version can be reverse engineered from the available data sets.
If reconciliation between data from different data sources is necessary, the *AAT* is used to map between them.

### Data processing

<!-- How will you work with the data?
Do you have/need storage?
Do you do backups?
Are you using object-store? Are you using relational database? Graph database? Triple store?
How are changes in data managed? -->

Data is processed predominantly in the R programming language and environment using varius packages and custom written scripts (see @sec-software for detailed overview of software used and how reproducibility is handled).
Changes in data, code and text are recorded using a version control system [git](https://git-scm.com/) and preserved online in a repository at [GitHub](https://github.com/).

<!-- ### Interpretation

Specify/list data formats you will be using and their structure.
Will different data be integrated? -->

### Data preservation

What data sets are you producing?
Is data long-term archived? Will it be usable and accessible after a long period of time?

### Access to data and code

The data used in this work will be as open as possible, as most of the data is licensed under one of the CC BY-NC or CC BY-SA licenses.
The code developed here is published under a very permissive and simple MIT license, where appropriate.
As already mentioned, the whole repository will be deposited at Zenodo data repository, as well as archived by the university and already is availbale throuh GitHub interface, including the record of the changes.

## Chapter summary {.unnumbered}
